// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nemocnice.Data;

namespace Nemocnice.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Nemocnice.Data.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HouseNumber")
                        .HasColumnType("int");

                    b.Property<string>("StreetName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ZIP")
                        .HasColumnType("int");

                    b.HasKey("AddressId");

                    b.ToTable("AddressT");
                });

            modelBuilder.Entity("Nemocnice.Data.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("OutsorceCompany")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminId");

                    b.ToTable("AdminT");
                });

            modelBuilder.Entity("Nemocnice.Data.Allergy", b =>
                {
                    b.Property<int>("AllergyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AllergyId");

                    b.ToTable("AllergyT");
                });

            modelBuilder.Entity("Nemocnice.Data.AllergyHealth", b =>
                {
                    b.Property<int>("AllergyHealthId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AllergyId")
                        .HasColumnType("int");

                    b.Property<int?>("HealthConditionId")
                        .HasColumnType("int");

                    b.HasKey("AllergyHealthId");

                    b.HasIndex("AllergyId");

                    b.HasIndex("HealthConditionId");

                    b.ToTable("AllegyHealthsT");
                });

            modelBuilder.Entity("Nemocnice.Data.CheckupTicket", b =>
                {
                    b.Property<int>("CheckupTicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByDoctorId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int?>("ToDoctorDoctorId")
                        .HasColumnType("int");

                    b.HasKey("CheckupTicketId");

                    b.HasIndex("CreatedByDoctorId");

                    b.HasIndex("PatientId");

                    b.HasIndex("ToDoctorDoctorId");

                    b.ToTable("CheckupTicketT");
                });

            modelBuilder.Entity("Nemocnice.Data.CureProgress", b =>
                {
                    b.Property<int>("CureProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DiagnosisId")
                        .HasColumnType("int");

                    b.Property<int>("MedicallReportId")
                        .HasColumnType("int");

                    b.Property<string>("StateOfTreatment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CureProgressId");

                    b.HasIndex("DiagnosisId");

                    b.HasIndex("MedicallReportId");

                    b.ToTable("CureProgressT");
                });

            modelBuilder.Entity("Nemocnice.Data.Diagnosis", b =>
                {
                    b.Property<int>("DiagnosisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DiagnosisId");

                    b.ToTable("DiagnosisT");
                });

            modelBuilder.Entity("Nemocnice.Data.DiagnosisActivityPricing", b =>
                {
                    b.Property<int>("DiagnosisActivityPricingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CurrentDiagnosisDiagnosisId")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentPricingMedicallActivityPriceId")
                        .HasColumnType("int");

                    b.HasKey("DiagnosisActivityPricingId");

                    b.HasIndex("CurrentDiagnosisDiagnosisId");

                    b.HasIndex("CurrentPricingMedicallActivityPriceId");

                    b.ToTable("DiagnosisActivityPricingsT");
                });

            modelBuilder.Entity("Nemocnice.Data.DiagnosisTicket", b =>
                {
                    b.Property<int>("DiagnosisTicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CheckupTicketId")
                        .HasColumnType("int");

                    b.Property<int?>("DiagnosisId")
                        .HasColumnType("int");

                    b.HasKey("DiagnosisTicketId");

                    b.HasIndex("CheckupTicketId");

                    b.HasIndex("DiagnosisId");

                    b.ToTable("DiagnosisTicketsT");
                });

            modelBuilder.Entity("Nemocnice.Data.Doctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ICZ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DoctorId");

                    b.ToTable("DoctorT");
                });

            modelBuilder.Entity("Nemocnice.Data.HealthCondition", b =>
                {
                    b.Property<int>("HealthConditionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BloodType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<DateTime>("LastCheckupDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("HealthConditionId");

                    b.ToTable("HealthConditionT");
                });

            modelBuilder.Entity("Nemocnice.Data.InsureEmp", b =>
                {
                    b.Property<int>("InsureEmpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("InsuranceEmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Possition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InsureEmpId");

                    b.ToTable("InsureEmpT");
                });

            modelBuilder.Entity("Nemocnice.Data.Login", b =>
                {
                    b.Property<int>("LoginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LoginId");

                    b.ToTable("LoginT");
                });

            modelBuilder.Entity("Nemocnice.Data.MedicallActivityPrice", b =>
                {
                    b.Property<int>("MedicallActivityPriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MedicallBillId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MedicallActivityPriceId");

                    b.HasIndex("MedicallBillId");

                    b.ToTable("MedicallActivityPriceT");
                });

            modelBuilder.Entity("Nemocnice.Data.MedicallBill", b =>
                {
                    b.Property<int>("MedicallBillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiagnosisId")
                        .HasColumnType("int");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("PersonalNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MedicallBillId");

                    b.HasIndex("DiagnosisId");

                    b.HasIndex("DoctorId");

                    b.ToTable("MedicallBillT");
                });

            modelBuilder.Entity("Nemocnice.Data.MedicallReport", b =>
                {
                    b.Property<int>("MedicallReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorDoctorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("MedicallReportId");

                    b.HasIndex("AuthorDoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("MedicallReportT");
                });

            modelBuilder.Entity("Nemocnice.Data.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("HealthConditionId")
                        .HasColumnType("int");

                    b.Property<int>("HomeAddressAddressId")
                        .HasColumnType("int");

                    b.Property<int>("InsuranceCompany")
                        .HasColumnType("int");

                    b.HasKey("PatientId");

                    b.HasIndex("HealthConditionId");

                    b.HasIndex("HomeAddressAddressId");

                    b.ToTable("PatientT");
                });

            modelBuilder.Entity("Nemocnice.Data.PatientTreatmentLog", b =>
                {
                    b.Property<int>("PatientTreatmentLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DiagnosisId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndOfTreatment")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartOfTreatment")
                        .HasColumnType("datetime2");

                    b.HasKey("PatientTreatmentLogId");

                    b.HasIndex("DiagnosisId");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientTreatmentLogT");
                });

            modelBuilder.Entity("Nemocnice.Data.Picture", b =>
                {
                    b.Property<int>("PictureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AllergyId")
                        .HasColumnType("int");

                    b.Property<int?>("CheckupTicketId")
                        .HasColumnType("int");

                    b.Property<byte[]>("CurrentPicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("MedicallReportId")
                        .HasColumnType("int");

                    b.HasKey("PictureId");

                    b.HasIndex("AllergyId");

                    b.HasIndex("CheckupTicketId");

                    b.HasIndex("MedicallReportId");

                    b.ToTable("PictureT");
                });

            modelBuilder.Entity("Nemocnice.Data.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AdminId")
                        .HasColumnType("int");

                    b.Property<int?>("LoginId")
                        .HasColumnType("int");

                    b.Property<string>("RoleType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.HasIndex("AdminId");

                    b.HasIndex("LoginId");

                    b.ToTable("RoleT");
                });

            modelBuilder.Entity("Nemocnice.Data.Text", b =>
                {
                    b.Property<int>("TextId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CheckupTicketId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentText")
                        .HasColumnType("int");

                    b.Property<int?>("MedicallReportId")
                        .HasColumnType("int");

                    b.HasKey("TextId");

                    b.HasIndex("CheckupTicketId");

                    b.HasIndex("MedicallReportId");

                    b.ToTable("TextT");
                });

            modelBuilder.Entity("Nemocnice.Data.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AdminId")
                        .HasColumnType("int");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InsureEmpId")
                        .HasColumnType("int");

                    b.Property<int>("LoginId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WorkAddressAddressId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("AdminId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("InsureEmpId");

                    b.HasIndex("LoginId");

                    b.HasIndex("WorkAddressAddressId");

                    b.ToTable("UserT");
                });

            modelBuilder.Entity("Nemocnice.Data.AllergyHealth", b =>
                {
                    b.HasOne("Nemocnice.Data.Allergy", "Allergy")
                        .WithMany()
                        .HasForeignKey("AllergyId");

                    b.HasOne("Nemocnice.Data.HealthCondition", "HealthCondition")
                        .WithMany()
                        .HasForeignKey("HealthConditionId");
                });

            modelBuilder.Entity("Nemocnice.Data.CheckupTicket", b =>
                {
                    b.HasOne("Nemocnice.Data.Doctor", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByDoctorId");

                    b.HasOne("Nemocnice.Data.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nemocnice.Data.Doctor", "ToDoctor")
                        .WithMany()
                        .HasForeignKey("ToDoctorDoctorId");
                });

            modelBuilder.Entity("Nemocnice.Data.CureProgress", b =>
                {
                    b.HasOne("Nemocnice.Data.Diagnosis", "Diagnosis")
                        .WithMany()
                        .HasForeignKey("DiagnosisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nemocnice.Data.MedicallReport", "MedicallReport")
                        .WithMany()
                        .HasForeignKey("MedicallReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nemocnice.Data.DiagnosisActivityPricing", b =>
                {
                    b.HasOne("Nemocnice.Data.Diagnosis", "CurrentDiagnosis")
                        .WithMany()
                        .HasForeignKey("CurrentDiagnosisDiagnosisId");

                    b.HasOne("Nemocnice.Data.MedicallActivityPrice", "CurrentPricing")
                        .WithMany()
                        .HasForeignKey("CurrentPricingMedicallActivityPriceId");
                });

            modelBuilder.Entity("Nemocnice.Data.DiagnosisTicket", b =>
                {
                    b.HasOne("Nemocnice.Data.CheckupTicket", "CheckupTicket")
                        .WithMany()
                        .HasForeignKey("CheckupTicketId");

                    b.HasOne("Nemocnice.Data.Diagnosis", "Diagnosis")
                        .WithMany()
                        .HasForeignKey("DiagnosisId");
                });

            modelBuilder.Entity("Nemocnice.Data.MedicallActivityPrice", b =>
                {
                    b.HasOne("Nemocnice.Data.MedicallBill", null)
                        .WithMany("MedicallActivityPrice")
                        .HasForeignKey("MedicallBillId");
                });

            modelBuilder.Entity("Nemocnice.Data.MedicallBill", b =>
                {
                    b.HasOne("Nemocnice.Data.Diagnosis", "Diagnosis")
                        .WithMany()
                        .HasForeignKey("DiagnosisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nemocnice.Data.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nemocnice.Data.MedicallReport", b =>
                {
                    b.HasOne("Nemocnice.Data.Doctor", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorDoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nemocnice.Data.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nemocnice.Data.Patient", b =>
                {
                    b.HasOne("Nemocnice.Data.HealthCondition", "HealthCondition")
                        .WithMany()
                        .HasForeignKey("HealthConditionId");

                    b.HasOne("Nemocnice.Data.Address", "HomeAddress")
                        .WithMany()
                        .HasForeignKey("HomeAddressAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nemocnice.Data.PatientTreatmentLog", b =>
                {
                    b.HasOne("Nemocnice.Data.Diagnosis", "Diagnosis")
                        .WithMany()
                        .HasForeignKey("DiagnosisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nemocnice.Data.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nemocnice.Data.Picture", b =>
                {
                    b.HasOne("Nemocnice.Data.Allergy", null)
                        .WithMany("Img")
                        .HasForeignKey("AllergyId");

                    b.HasOne("Nemocnice.Data.CheckupTicket", null)
                        .WithMany("Img")
                        .HasForeignKey("CheckupTicketId");

                    b.HasOne("Nemocnice.Data.MedicallReport", null)
                        .WithMany("Img")
                        .HasForeignKey("MedicallReportId");
                });

            modelBuilder.Entity("Nemocnice.Data.Role", b =>
                {
                    b.HasOne("Nemocnice.Data.Admin", null)
                        .WithMany("Roles")
                        .HasForeignKey("AdminId");

                    b.HasOne("Nemocnice.Data.Login", null)
                        .WithMany("Roles")
                        .HasForeignKey("LoginId");
                });

            modelBuilder.Entity("Nemocnice.Data.Text", b =>
                {
                    b.HasOne("Nemocnice.Data.CheckupTicket", null)
                        .WithMany("Description")
                        .HasForeignKey("CheckupTicketId");

                    b.HasOne("Nemocnice.Data.MedicallReport", null)
                        .WithMany("AccessRights")
                        .HasForeignKey("MedicallReportId");
                });

            modelBuilder.Entity("Nemocnice.Data.User", b =>
                {
                    b.HasOne("Nemocnice.Data.Admin", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId");

                    b.HasOne("Nemocnice.Data.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId");

                    b.HasOne("Nemocnice.Data.InsureEmp", "InsureEmp")
                        .WithMany()
                        .HasForeignKey("InsureEmpId");

                    b.HasOne("Nemocnice.Data.Login", "Login")
                        .WithMany()
                        .HasForeignKey("LoginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nemocnice.Data.Address", "WorkAddress")
                        .WithMany()
                        .HasForeignKey("WorkAddressAddressId");
                });
#pragma warning restore 612, 618
        }
    }
}
